<section class="admin__page-section custom-tab-content">
    <button class="button" id="payu_gateway_txn_status">Get Transaction Data</button>
    <br />
    <div id="txn_data"></div>
</section>
<script>
    require([
        "prototype"
    ], function () {
        if (!window.PayUAjaxCheck) {
            window.PayUAjaxCheck = '<?= $block->getAjaxUrl(); ?>';
            window.PayUAjaxFormKey = '<?= $block->getFormKey(); ?>';
            window.PayUAjaxOrderId = '<?= $block->getOrder()->getId(); ?>';
        }
    });
</script>
